username = input("Введите Ваше имя: ")
title = input("Название заметки: ")
content = input("Описание: ")
created_date = input("Дата создания в формате ДД.ММ.ГГГГ: ")
issue_date = input("Дата истечения заметки в формате ДД.ММ.ГГГГ: ")